# File: .github/workflows/conditional.yml
name: Conditional Workflow Challenge

on:
  push:
    branches:
      - release
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  conditional-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      #  Branch-Based Conditional
      - name: Run only on release branch
        if: github.ref == 'refs/heads/release'
        run: |
          echo " Running exclusive step for 'release' branch."

      #  Pull Request Check
      - name: Run during Pull Request event
        if: github.event_name == 'pull_request'
        run: |
          echo " PR Title: ${{ github.event.pull_request.title }}"
          echo " PR Author: ${{ github.event.pull_request.user.login }}"

      #  Commit Message Keyword Trigger
      - name: Run Tests if Commit Message Includes '[run-tests]'
        if: github.event_name == 'push' && contains(github.event.head_commit.message, '[run-tests]')
        run: |
          echo " Executing tests as requested..."

      #  Repository Owner Verification
      - name: Run only if triggered by repository owner
        if: github.actor == github.repository_owner
        run: |
          echo " Workflow triggered by repository owner: ${{ github.actor }}."
